[[profiles]]
id = '905E9CE3-5DB3-4624-A4C5-722E76D4DF32'
name = 'Default'

[[profiles.workspaces]]
display = 'Main'
id = '91C84EE3-B74A-41A7-8EA0-E9119A11AAD0'
name = 'Web'
openAppsOnActivation = false
symbolIconName = 'globe'

[profiles.workspaces.appToFocus]
bundleIdentifier = 'com.brave.Browser'
iconPath = '/Applications/Brave Browser.app/Contents/Resources/app.icns'
name = 'Brave Browser'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.markmcguill.strongbox.mac'
iconPath = '/Applications/Strongbox.app/Contents/Resources/AppIcon-BigSur-NU.icns'
name = 'Strongbox'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.brave.Browser'
iconPath = '/Applications/Brave Browser.app/Contents/Resources/app.icns'
name = 'Brave Browser'

[[profiles.workspaces]]
display = 'Main'
id = '65806886-EEEB-4FD1-8CE3-0798BA0E38D4'
name = 'Files'
openAppsOnActivation = false
symbolIconName = 'document'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.microsoft.Excel'
iconPath = '/Applications/Microsoft Excel.app/Contents/Resources/XCEL.icns'
name = 'Microsoft Excel'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.jgraph.drawio.desktop'
iconPath = '/Applications/draw.io.app/Contents/Resources/icon.icns'
name = 'draw.io'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.sublimetext.4'
iconPath = '/Applications/Sublime Text.app/Contents/Resources/Sublime Text.icns'
name = 'Sublime Text'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.apple.Preview'
iconPath = '/System/Applications/Preview.app/Contents/Resources/AppIcon.icns'
name = 'Preview'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.cron.electron'
iconPath = '/Applications/Notion Calendar.app/Contents/Resources/electron.icns'
name = 'Notion Calendar'

[[profiles.workspaces]]
display = 'Secondary'
id = '24D7D507-5FBC-4F01-A58E-2E9717A5ABD8'
name = 'Songs'
openAppsOnActivation = true
symbolIconName = 'music.note'

[profiles.workspaces.appToFocus]
bundleIdentifier = 'com.spotify.client'
iconPath = '/Applications/Spotify.app/Contents/Resources/AppIcon.icns'
name = 'Spotify'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.spotify.client'
iconPath = '/Applications/Spotify.app/Contents/Resources/AppIcon.icns'
name = 'Spotify'

[[profiles.workspaces]]
display = 'Main'
id = 'ADB483EF-C1F8-4B3D-80C7-E79D4681E3C4'
name = 'Programming'
openAppsOnActivation = false
symbolIconName = 'curlybraces'

[profiles.workspaces.appToFocus]
bundleIdentifier = 'com.jetbrains.rustrover'
iconPath = '/Users/Moritz/Applications/RustRover.app/Contents/Resources/rustrover.icns'
name = 'RustRover'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.jetbrains.pycharm'
iconPath = '/Users/Moritz/Applications/PyCharm.app/Contents/Resources/pycharm.icns'
name = 'PyCharm'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.jetbrains.intellij'
iconPath = '/Users/Moritz/Applications/IntelliJ IDEA Ultimate.app/Contents/Resources/idea.icns'
name = 'IntelliJ IDEA'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.apple.dt.Xcode'
iconPath = '/Applications/Xcode.app/Contents/Resources/Xcode.icns'
name = 'Xcode'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.microsoft.VSCode'
iconPath = '/Applications/Visual Studio Code.app/Contents/Resources/Code.icns'
name = 'Code'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.jetbrains.WebStorm'
iconPath = '/Users/Moritz/Applications/WebStorm.app/Contents/Resources/webstorm.icns'
name = 'WebStorm'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.jetbrains.rustrover'
iconPath = '/Users/Moritz/Applications/RustRover.app/Contents/Resources/rustrover.icns'
name = 'RustRover'

[[profiles.workspaces]]
display = 'Built-in Retina Display'
id = '40D620E1-2182-4EB9-9366-220E7AF8B66B'
name = 'Zoom'
openAppsOnActivation = false
symbolIconName = 'video'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.microsoft.teams2'
iconPath = '/Applications/Microsoft Teams.app/Contents/Resources/icon.icns'
name = 'Microsoft Teams'

[[profiles.workspaces.apps]]
bundleIdentifier = 'us.zoom.xos'
iconPath = '/Applications/zoom.us.app/Contents/Resources/ZPLogo.icns'
name = 'zoom.us'

[[profiles.workspaces]]
display = 'Secondary'
id = '8E9A2780-8954-4E3C-8C45-565C22A8F979'
name = 'Read'
openAppsOnActivation = false
symbolIconName = 'book'

[[profiles.workspaces.apps]]
bundleIdentifier = 'md.obsidian'
iconPath = '/Applications/Obsidian.app/Contents/Resources/icon.icns'
name = 'Obsidian'

[[profiles.workspaces.apps]]
bundleIdentifier = 'io.remnote'
iconPath = '/Applications/RemNote.app/Contents/Resources/icon.icns'
name = 'RemNote'

[[profiles.workspaces]]
display = 'Secondary'
id = 'CBE328E7-B952-4B65-8285-D78846855E63'
name = 'Terminal'
openAppsOnActivation = true
symbolIconName = 'apple.terminal'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.mitchellh.ghostty'
iconPath = '/Applications/Ghostty.app/Contents/Resources/AppIcon.icns'
name = 'Ghostty'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.example.GroupCtrl'
iconPath = '/Users/Moritz/Dev/GroupCtrl/target/dx/GroupCtrl/debug/macos/GroupCtrl.app/Contents/Resources/icon.icns'
name = 'GroupCtrl'

[[profiles.workspaces]]
display = 'Secondary'
id = '5C608563-2C59-4929-AAA5-C091BF25903C'
name = 'eXtra web'
openAppsOnActivation = true
symbolIconName = 'binoculars.fill'

[profiles.workspaces.appToFocus]
bundleIdentifier = 'com.google.Chrome'
iconPath = '/Applications/Google Chrome.app/Contents/Resources/app.icns'
name = 'Google Chrome'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.google.Chrome'
iconPath = '/Applications/Google Chrome.app/Contents/Resources/app.icns'
name = 'Google Chrome'

[[profiles.workspaces]]
display = 'DELL S2725QC'
id = '3C83931C-30AF-4240-A7E2-AAF0B839118E'
name = 'Check'
openAppsOnActivation = true
symbolIconName = 'checklist'

[profiles.workspaces.appToFocus]
bundleIdentifier = 'com.linear'
iconPath = '/Applications/Linear.app/Contents/Resources/icon.icns'
name = 'Linear'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.linear'
iconPath = '/Applications/Linear.app/Contents/Resources/icon.icns'
name = 'Linear'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.TickTick.task.mac'
iconPath = '/Applications/TickTick.app/Contents/Resources/AppIcon.icns'
name = 'TickTick'

[[profiles.workspaces]]
display = 'Secondary'
id = '95F04D28-6A5A-45A6-BB5A-333B8A1614AF'
name = 'AI'
openAppsOnActivation = false
symbolIconName = 'bonjour'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.apple.Safari.WebApp.B314DBF0-7616-480C-875E-F25CB400DA39'
iconPath = '/Users/Moritz/Applications/Gemini.app/Contents/Resources/ApplicationIcon.icns'
name = 'Gemini'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.anthropic.claudefordesktop'
iconPath = '/Applications/Claude.app/Contents/Resources/electron.icns'
name = 'Claude'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.apple.Safari.WebApp.4E0A62BE-C683-4E45-B299-040807FB283A'
iconPath = '/Users/Moritz/Applications/Google AI Studio.app/Contents/Resources/ApplicationIcon.icns'
name = 'Google AI Studio'