activeWorkspaceOnFocusChange = true
alternativeDisplays = 'Main=DELL S2725QC; Secondary=DELL G2724D; Main=PHL 45B1U6900 (1); Secondary=PHL 45B1U6900 (2) '
centerCursorOnFocusChange = false
centerCursorOnWorkspaceChange = false
changeWorkspaceOnAppAssign = true
checkForUpdatesAutomatically = true
displayMode = 'dynamic'
enableFocusManagement = true
enableIntegrations = false
enablePictureInPictureSupport = false
enableSpaceControl = false
enableSpaceControlAnimations = true
enableSpaceControlTilesAnimations = true
enableSwipeGestures = false
enableWorkspaceTransitions = false
focusFrontmostWindow = false
focusLeft = 'cmd+ctrl+opt+1'
focusNextWorkspaceApp = 'cmd+ctrl+opt+q'
focusRight = 'cmd+ctrl+opt+4'
keepUnassignedAppsOnSwitch = true
loopWorkspaces = true
loopWorkspacesOnAllDisplays = false
menuBarDisplayAliases = ''
menuBarTitleTemplate = '$WORKSPACE'
pipApps = []
pipScreenCornerOffset = 15
restartAppOnWakeUp = false
restoreHiddenAppsOnSwitch = true
runScriptAfterWorkspaceChange = ''
runScriptOnLaunch = ''
runScriptOnProfileChange = 'sketchybar --reload'
runScriptOnWorkspaceChange = 'sketchybar --trigger flashspace_workspace_change WORKSPACE="$WORKSPACE" DISPLAY="$DISPLAY"'
showFlashSpace = 'cmd+m'
showFloatingNotifications = true
showMenuBarIcon = true
showMenuBarTitle = true
skipEmptyWorkspacesOnSwitch = false
spaceControlCurrentDisplayWorkspaces = false
spaceControlHideEmptyWorkspaces = false
spaceControlNumberOfColumns = 0
spaceControlUpdateScreenshotsOnOpen = false
swipeDown3FingerAction = 'none'
swipeDown4FingerAction = 'none'
swipeLeft3FingerAction = 'previousWorkspace'
swipeLeft4FingerAction = 'none'
swipeRight3FingerAction = 'nextWorkspace'
swipeRight4FingerAction = 'none'
swipeThreshold = 0.20000000000000001
swipeUp3FingerAction = 'none'
swipeUp4FingerAction = 'none'
switchWorkspaceOnCursorScreen = false
switchWorkspaceWhenPipCloses = true
toggleTheFocusedAppFloating = 'cmd+ctrl+opt+`'
workspaceTransitionDimming = 0.20000000000000001
workspaceTransitionDuration = 0.29999999999999999