# espanso match file
matches:
  - trigger: ";home"
    replace: 🏠
  - trigger: ";pro"
    replace: ✅
  - trigger: ";neutral"
    replace: 🟡
  - trigger: ";con"
    replace: ❌
  
  - trigger: ";tel"
    replace: "+49 1573 8201665"
  - trigger: ";mail"
    replace: moritz.broedel@gmail.com
  - trigger: ";kitmail"
    replace: upzdz@student.kit.edu
  - trigger: ";aaltomail"
    replace: moritz.brodel@aalto.fi
  - trigger: ";exactmail"
    replace: brod444186@exactmail.com

  - trigger: ";shrug"
    replace: ¯\_(ツ)_/¯
  - trigger: ";mdshrug"
    replace: ¯\\\_(ツ)\_/¯

  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"
